### PR TITLE
add shadow mmr subgraph

### PR DESCRIPTION
**Pull request by xiaoch05**
save pair (position=>hash) by subgraph

### CODE REVIEW

**Comment by HackFisher** [comment]
@xiaoch05 How is the test effect of the mmr subgraph?

**Comment by xiaoch05** [comment]
> @xiaoch05 How is the test effect of the mmr subgraph?

test some data(about 1000 blocks), the position saved is right.
Next we need a server to deploy it and the bridger needs to update the usage of this api with the lib https://github.com/darwinia-network/shadow/pull/165

**Comment by HackFisher** [comment]
@fewensa @furoxr This subgraph is to replace the mmr node indexing service of shadow we currently is using.

Here is an generate mmr proof implementation in client side demonstrate how to get a mmr proof using graphQL from subql/subgraph.

It will be helpful to bridger as a reference since bridger will have to implement this util method which shadow will no longer provide.

**Review by HackFisher — APPROVED** [review]

**Comment by HackFisher** [comment]
@xiaoch05 what's the latest update of ropsten theGraph service issue?

**Comment by xiaoch05** [comment]
> 

currently, there is no machine to deploy the graph node for ropsten. And waiting the bridge to do the migration. cc @fewensa

**Comment by HackFisher** [comment]
After review, the subgraph is better to locate in bridger repo. cc @xiaoch05 @fewensa

**Comment by HackFisher** [comment]
After review, the subgraph is better to locate in bridger repo. cc @xiaoch05 @fewensa

**Pull request closed without merging**
