### PR TITLE
add crab address

### PR DESCRIPTION
**Pull request by xiaoch05**

### CODE REVIEW

**Comment by HackFisher** [comment]
We can add the xRING mapping token address in crab too:

https://crab.subscan.io/extrinsic/8304404-1


0x7399Ea6C9d35124d893B8d9808930e9d3F211501

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/darwinia/issues/726

**Comment by hujw77** [comment]
```
WormholeDaoMultisig: 0x0050F880c35c31c13BFd9cBb7D28AafaEcA3abd2
WormholeDaoTimeLock: 0x2401224012bAE7C2f217392665CA7abC16dCDE1e
```

**Comment by HackFisher** [comment]
Related: https://github.com/darwinia-network/darwinia-bridge-sol/issues/110

**Review by HackFisher — APPROVED** [review]

**Pull request merged**
